services:
  - type: web
    name: class-connect-backend
    env: node
    region: ohio
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
